FROM node:14.16.1 AS build

LABEL author="Mark Zhu"

WORKDIR /frontend

COPY package*.json ./

RUN npm install 

COPY . ./

RUN npm run build

FROM nginx:stable-alpine
# install aws cli through python as python seems to always have the latest version of aws cli.
RUN apk add python3 py-pip

RUN pip3 install awscli --upgrade

RUN apk add --update docker openrc

COPY --from=build /frontend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
