FROM node:14.16.1 AS build

LABEL author="Mark Zhu"

WORKDIR /backend

COPY package*.json ./

RUN npm install 

COPY . ./

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /backend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
